// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studomat.DAL;

namespace Studomat.DAL.Migrations
{
    [DbContext(typeof(StudentManagerDbContext))]
    [Migration("20201110161333_DodavanjeKolegijaINastavnika")]
    partial class DodavanjeKolegijaINastavnika
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Studomat.MODEL.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<DateTime>("DatumUpisa");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<int?>("FakultetId");

                    b.Property<string>("Ime");

                    b.Property<string>("JMBAG");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<int?>("MjestoId");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("OIB");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Prezime");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FakultetId");

                    b.HasIndex("MjestoId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Studomat.MODEL.Fakultet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Email");

                    b.Property<string>("GodinaOsnutka");

                    b.Property<int?>("MjestoId");

                    b.Property<string>("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("MjestoId");

                    b.ToTable("Fakulteti");

                    b.HasData(
                        new { ID = 1, Adresa = "Svetošimunska cesta 25", GodinaOsnutka = "1919", MjestoId = 1, Naziv = "Agronomski fakultet u Zagrebu" },
                        new { ID = 2, Adresa = "Trg Republike Hrvatske 5", GodinaOsnutka = "1896", MjestoId = 1, Naziv = "Akademija dramske umjetnosti u Zagrebu" },
                        new { ID = 3, Adresa = "Ilica 85", GodinaOsnutka = "1907", MjestoId = 1, Naziv = "Akademija likovnih umjetnosti u Zagrebu" },
                        new { ID = 4, Adresa = "Slavka Krautzeka 83", GodinaOsnutka = "2005", MjestoId = 3, Naziv = "Akademija primijenjenih umjetnosti u Rijeci" },
                        new { ID = 5, Adresa = "Fra Andrije Kačića Miošića 26", GodinaOsnutka = "1919", MjestoId = 1, Naziv = "Arhitektonski fakultet u Zagrebu" },
                        new { ID = 6, Adresa = " Borongajska cesta 83f", GodinaOsnutka = "1962", MjestoId = 1, Naziv = "Edukacijsko-rehabilitacijski fakultet u Zagrebu" },
                        new { ID = 7, Adresa = "Trg Ljudevita Gaja 7", GodinaOsnutka = "1959", MjestoId = 4, Naziv = "Ekonomski fakultet u Osijeku" },
                        new { ID = 8, Adresa = "Cvite Fiskovića 5", GodinaOsnutka = "1975", MjestoId = 2, Naziv = "Ekonomski fakultet u Splitu" },
                        new { ID = 9, Adresa = "Trg John F. Kennedy 6", GodinaOsnutka = "1920", MjestoId = 1, Naziv = "Ekonomski fakultet u Zagrebu" },
                        new { ID = 10, Adresa = "Unska ul. 3", GodinaOsnutka = "1956", MjestoId = 1, Naziv = "Fakultet elektrotehnike i računarstva" },
                        new { ID = 11, Adresa = "Kneza Trpimira 2B", GodinaOsnutka = "1978", MjestoId = 4, Naziv = "Fakultet elektrotehnike, računarstva i informacijskih tehnologija u Osijeku" },
                        new { ID = 12, Adresa = "Ul. Ruđera Boškovića 32", GodinaOsnutka = "1960", MjestoId = 2, Naziv = "Fakultet elektrotehnike, strojarstva i brodogradnje u Splitu" },
                        new { ID = 13, Adresa = "Borongajska cesta 83d", GodinaOsnutka = "1992", MjestoId = 1, Naziv = "Fakultet hrvatskih studija" },
                        new { ID = 14, Adresa = "Trg Marka Marulića 19", GodinaOsnutka = "1919", MjestoId = 1, Naziv = "Fakultet kemijskog inženjerstva i tehnologije u Zagrebu" },
                        new { ID = 15, Adresa = "Pavlinska ul. 2", GodinaOsnutka = "1974", MjestoId = 13, Naziv = "Fakultet organizacije i informatike u Varaždinu" },
                        new { ID = 16, Adresa = "Lepušićeva ul. 6", GodinaOsnutka = "1962", MjestoId = 1, Naziv = "Fakultet političkih znanosti u Zagrebu" },
                        new { ID = 17, Adresa = "Vukelićeva ul. 4", GodinaOsnutka = "1984", MjestoId = 1, Naziv = "Fakultet prometnih znanosti u Zagrebu" },
                        new { ID = 18, Adresa = "Ul. Ivana Lučića 5", GodinaOsnutka = "1956", MjestoId = 1, Naziv = "Fakultet strojarstva i brodogradnje" },
                        new { ID = 19, Adresa = "Ul. cara Hadrijana 10", GodinaOsnutka = "1961", MjestoId = 4, Naziv = "Fakultet za odgojne i obrazovne znanosti u Osijeku" },
                        new { ID = 20, Adresa = "Ul. Ante Kovačića 1", GodinaOsnutka = "1882", MjestoId = 1, Naziv = "Farmaceutsko-biokemijski fakultet u Zagrebu" },
                        new { ID = 21, Adresa = "Ul. Lorenza Jagera 9", GodinaOsnutka = "2004", MjestoId = 4, Naziv = "Filozofski fakultet u Osijeku" },
                        new { ID = 22, Adresa = "Sveučilišna Av 4", GodinaOsnutka = "1953", MjestoId = 3, Naziv = "Filozofski fakultet u Rijeci" },
                        new { ID = 23, Adresa = "Poljička cesta 35", GodinaOsnutka = "2005", MjestoId = 2, Naziv = "Filozofski fakultet u Splitu" },
                        new { ID = 24, Adresa = "Ul. Mihovila Pavlinovića", GodinaOsnutka = "2002", MjestoId = 5, Naziv = "Filozofski fakultet u Zadru" },
                        new { ID = 25, Adresa = "Ul. Ivana Lučića 3", GodinaOsnutka = "1874", MjestoId = 1, Naziv = "Filozofski fakultet u Zagrebu" },
                        new { ID = 26, Adresa = "Kačićeva ul. 26", GodinaOsnutka = "1962", MjestoId = 1, Naziv = "Geodetski fakultet u Zagrebu" },
                        new { ID = 27, Adresa = "Hallerova aleja 7", GodinaOsnutka = "1969", MjestoId = 13, Naziv = "Geotehnički fakultet u Varaždinu" },
                        new { ID = 28, Adresa = "Kačićeva ul. 26", GodinaOsnutka = "1919", MjestoId = 1, Naziv = "Građevinski fakultet u Zagrebu" },
                        new { ID = 29, Adresa = "Vladimira Preloga 3", GodinaOsnutka = "1967", MjestoId = 4, Naziv = "Građevinski i arhitektonski fakultet u Osijeku" },
                        new { ID = 30, Adresa = "Getaldićeva ul. 2", GodinaOsnutka = "1959", MjestoId = 1, Naziv = "Grafički fakultet u Zagrebu" },
                        new { ID = 31, Adresa = "Petra Preradovića 17", GodinaOsnutka = "1806", MjestoId = 20, Naziv = "Katolički bogoslovni fakultet u Đakovu" },
                        new { ID = 32, Adresa = "Ul. Zrinsko Frankopanska 19", GodinaOsnutka = "1999", MjestoId = 2, Naziv = "Katolički bogoslovni fakultet u Splitu" },
                        new { ID = 33, Adresa = "Vlaška ul. 38", GodinaOsnutka = "1670", MjestoId = 1, Naziv = "Katolički bogoslovni fakultet u Zagrebu" },
                        new { ID = 34, Adresa = "Horvaćanski zavoj 15", GodinaOsnutka = "1959", MjestoId = 1, Naziv = "Kineziološki fakultet u Zagrebu" },
                        new { ID = 35, Adresa = "Ul. Josipa Huttlera 4", GodinaOsnutka = "1998", MjestoId = 4, Naziv = "Medicinski fakultet u Osijeku" },
                        new { ID = 36, Adresa = "Ul. Braće Branchetta 20/1", GodinaOsnutka = "1955", MjestoId = 3, Naziv = "Medicinski fakultet u Rijeci" },
                        new { ID = 37, Adresa = "Šoltanska ul. 2", GodinaOsnutka = "1997", MjestoId = 2, Naziv = "Medicinski fakultet u Splitu" },
                        new { ID = 38, Adresa = "Šalata ul. 2", GodinaOsnutka = "1917", MjestoId = 1, Naziv = "Medicinski fakultet u Zagrebu" },
                        new { ID = 39, Adresa = "Aleja narodnih heroja 3", GodinaOsnutka = "1958", MjestoId = 11, Naziv = "Metalurški fakultet u Sisku" },
                        new { ID = 40, Adresa = "Ul. cara Hadrijana 8/A", GodinaOsnutka = "2005", MjestoId = 4, Naziv = "Odjel za biologiju Sveučilišta Josipa Jurja Strossmayera u Osijeku" },
                        new { ID = 41, Adresa = "Trg Ljudevita Gaja 6", GodinaOsnutka = "2005", MjestoId = 4, Naziv = "Odjel za fiziku Sveučilišta Josipa Jurja Strossmayera u Osijeku" },
                        new { ID = 42, Adresa = "Ul. Radmile Matejčić 2", GodinaOsnutka = "2008", MjestoId = 3, Naziv = "Odjel za informatiku Sveučilišta u Rijeci" },
                        new { ID = 43, Adresa = "Vladimira Preloga 1", GodinaOsnutka = "1960", MjestoId = 4, Naziv = "Poljoprivredni fakultet u Osijeku" },
                        new { ID = 44, Adresa = "Ul. Ruđera Boškovića 37", GodinaOsnutka = "1959", MjestoId = 2, Naziv = "Pomorski fakultet u Splitu" },
                        new { ID = 45, Adresa = "Ul. Stjepana Radića 13", GodinaOsnutka = "1975", MjestoId = 4, Naziv = "Pravni fakultet u Osijeku" },
                        new { ID = 46, Adresa = "Ul. Domovinskog rata 8", GodinaOsnutka = "1961", MjestoId = 2, Naziv = "Pravni fakultet u Splitu" },
                        new { ID = 47, Adresa = "Trg Republike Hrvatske 14", GodinaOsnutka = "1776", MjestoId = 1, Naziv = "Pravni fakultet u Zagrebu" },
                        new { ID = 48, Adresa = "Pierottijeva ul. 6", GodinaOsnutka = "1956", MjestoId = 1, Naziv = "Prehrambeno-biotehnološki fakultet u Zagrebu" },
                        new { ID = 49, Adresa = "Ul. Franje Kuhača 20", GodinaOsnutka = "1976", MjestoId = 4, Naziv = "Prehrambeno-tehnološki fakultet u Osijeku" },
                        new { ID = 50, Adresa = "Ul. Ruđera Boškovića 33", GodinaOsnutka = "1945", MjestoId = 2, Naziv = "Prirodoslovno-matematički fakultet u Splitu" },
                        new { ID = 51, Adresa = "Horvatovac ul. 102a", GodinaOsnutka = "1946", MjestoId = 1, Naziv = "Prirodoslovno-matematički fakultet u Zagrebu" },
                        new { ID = 52, Adresa = "Gundulićeva ul. 5", GodinaOsnutka = "1962", MjestoId = 1, Naziv = "Stomatološki fakultet u Zagrebu" },
                        new { ID = 53, Adresa = "Ul. Ivana Gundulića 20A", GodinaOsnutka = "1970", MjestoId = 6, Naziv = "Strojarski fakultet u Slavonskom Brodu" },
                        new { ID = 54, Adresa = "Svetošimunska cesta 25", GodinaOsnutka = "1898", MjestoId = 1, Naziv = "Šumarski fakultet u Zagrebu" },
                        new { ID = 55, Adresa = "Vrbik 8", GodinaOsnutka = "1998", MjestoId = 1, Naziv = "Tehničko veleučilište u Zagrebu" },
                        new { ID = 56, Adresa = "Savska cesta 77", GodinaOsnutka = "2006", MjestoId = 1, Naziv = "Učiteljski fakultet u Zagrebu" },
                        new { ID = 57, Adresa = "Heinzelova ul. 55", GodinaOsnutka = "1919", MjestoId = 1, Naziv = "Veterinarski fakultet u Zagrebu" }
                    );
                });

            modelBuilder.Entity("Studomat.MODEL.Kolegij", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FakultetId");

                    b.Property<int?>("NastavnikId");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.HasKey("ID");

                    b.HasIndex("FakultetId");

                    b.HasIndex("NastavnikId");

                    b.ToTable("Kolegiji");

                    b.HasData(
                        new { ID = 1, FakultetId = 1, NastavnikId = 1, Naziv = "Uvod u mikrobiologiju tla" },
                        new { ID = 2, FakultetId = 1, NastavnikId = 2, Naziv = "Botanika" },
                        new { ID = 3, FakultetId = 1, NastavnikId = 3, Naziv = "Osnove agroekonomike" },
                        new { ID = 4, FakultetId = 1, NastavnikId = 4, Naziv = "Matematika" },
                        new { ID = 5, FakultetId = 1, NastavnikId = 5, Naziv = "Agroklimatologija" },
                        new { ID = 6, FakultetId = 2, NastavnikId = 6, Naziv = "Dramsko pismo" },
                        new { ID = 7, FakultetId = 2, NastavnikId = 7, Naziv = "Filmsko pismo" },
                        new { ID = 8, FakultetId = 2, NastavnikId = 8, Naziv = "Estetika filma" },
                        new { ID = 9, FakultetId = 2, NastavnikId = 9, Naziv = "Analiza filma" },
                        new { ID = 10, FakultetId = 2, NastavnikId = 10, Naziv = "Dramatologija" },
                        new { ID = 11, FakultetId = 3, NastavnikId = 11, Naziv = "Crtanje" },
                        new { ID = 12, FakultetId = 3, NastavnikId = 12, Naziv = "Uvod u slikanje" },
                        new { ID = 13, FakultetId = 3, NastavnikId = 13, Naziv = "Kiparstvo" },
                        new { ID = 14, FakultetId = 3, NastavnikId = 14, Naziv = "Uvod u likovnu umjetnost" },
                        new { ID = 15, FakultetId = 3, NastavnikId = 15, Naziv = "Sociologija kulture" },
                        new { ID = 16, FakultetId = 4, NastavnikId = 16, Naziv = "Književnost" },
                        new { ID = 17, FakultetId = 4, NastavnikId = 17, Naziv = "Svjetska književnost" },
                        new { ID = 18, FakultetId = 4, NastavnikId = 18, Naziv = "Povijest kazališta i drame" },
                        new { ID = 19, FakultetId = 4, NastavnikId = 19, Naziv = "Film i druge umjetnosti" },
                        new { ID = 20, FakultetId = 4, NastavnikId = 20, Naziv = "Radiofonija" },
                        new { ID = 21, FakultetId = 5, NastavnikId = 21, Naziv = "Zgrade za rad i trgovinu" },
                        new { ID = 22, FakultetId = 5, NastavnikId = 22, Naziv = "Osnove nacrtne geometrije" },
                        new { ID = 23, FakultetId = 5, NastavnikId = 23, Naziv = "Uvod u primjenu računala" },
                        new { ID = 24, FakultetId = 5, NastavnikId = 24, Naziv = "Pri­mje­na ra­ču­na­la u ar­hi­tek­tu­ri" },
                        new { ID = 25, FakultetId = 5, NastavnikId = 25, Naziv = "Uvod u pro­jek­ti­ra­nje stam­be­nih zgra­da" },
                        new { ID = 26, FakultetId = 6, NastavnikId = 26, Naziv = "Osnove humane genetike" },
                        new { ID = 27, FakultetId = 6, NastavnikId = 27, Naziv = "Funkcionalna anatomija i fiziologija" },
                        new { ID = 28, FakultetId = 6, NastavnikId = 28, Naziv = "Uvod u psihologiju djetinjstva i adolescencije" },
                        new { ID = 29, FakultetId = 6, NastavnikId = 29, Naziv = "Motorički poremećaji, kronične bolesti i sofrologija" },
                        new { ID = 30, FakultetId = 6, NastavnikId = 30, Naziv = "Statistika" },
                        new { ID = 31, FakultetId = 7, NastavnikId = 31, Naziv = "Počela ekonomije" },
                        new { ID = 32, FakultetId = 7, NastavnikId = 32, Naziv = "Statistika" },
                        new { ID = 33, FakultetId = 7, NastavnikId = 33, Naziv = "Osnove organizacije " },
                        new { ID = 34, FakultetId = 7, NastavnikId = 34, Naziv = "Sociologija" },
                        new { ID = 35, FakultetId = 7, NastavnikId = 35, Naziv = "Engleski jezik 1" },
                        new { ID = 36, FakultetId = 8, NastavnikId = 36, Naziv = "Aktuarska matematika" },
                        new { ID = 37, FakultetId = 8, NastavnikId = 37, Naziv = "Alternativni izvori financiranja" },
                        new { ID = 38, FakultetId = 8, NastavnikId = 38, Naziv = "Analiza financijskih izvješća" },
                        new { ID = 39, FakultetId = 8, NastavnikId = 39, Naziv = "Bankarstvo" },
                        new { ID = 40, FakultetId = 8, NastavnikId = 40, Naziv = "Burze i vrijednosnice" },
                        new { ID = 41, FakultetId = 9, NastavnikId = 41, Naziv = "Ekonometrija" },
                        new { ID = 42, FakultetId = 9, NastavnikId = 42, Naziv = "Ekonomija tržišta rada" },
                        new { ID = 43, FakultetId = 9, NastavnikId = 43, Naziv = "E-marketing" },
                        new { ID = 44, FakultetId = 9, NastavnikId = 44, Naziv = "Financijski sustav" },
                        new { ID = 45, FakultetId = 9, NastavnikId = 45, Naziv = "Gospodarstvo Hrvatske" },
                        new { ID = 46, FakultetId = 10, NastavnikId = 46, Naziv = "Digitalna logika" },
                        new { ID = 47, FakultetId = 10, NastavnikId = 47, Naziv = "Linearna algebra" },
                        new { ID = 48, FakultetId = 10, NastavnikId = 48, Naziv = "Matematička analiza 1" },
                        new { ID = 49, FakultetId = 10, NastavnikId = 49, Naziv = "Uvod u programiranje" },
                        new { ID = 50, FakultetId = 10, NastavnikId = 50, Naziv = "Algoritmi i strukture podataka" },
                        new { ID = 51, FakultetId = 11, NastavnikId = 51, Naziv = "Osnove elektrotehnike i elektronike" },
                        new { ID = 52, FakultetId = 11, NastavnikId = 52, Naziv = "Inženjerska grafika i dokumentiranje" },
                        new { ID = 53, FakultetId = 11, NastavnikId = 53, Naziv = "Programiranje I" },
                        new { ID = 54, FakultetId = 11, NastavnikId = 54, Naziv = "Matematičke osnove računarstva" },
                        new { ID = 55, FakultetId = 11, NastavnikId = 55, Naziv = "Engleski jezik" },
                        new { ID = 56, FakultetId = 12, NastavnikId = 56, Naziv = "Matematika 1 " },
                        new { ID = 57, FakultetId = 12, NastavnikId = 57, Naziv = "Materijali 1" },
                        new { ID = 58, FakultetId = 12, NastavnikId = 58, Naziv = "Mehanika 1" },
                        new { ID = 59, FakultetId = 12, NastavnikId = 59, Naziv = "Fizika" },
                        new { ID = 60, FakultetId = 12, NastavnikId = 60, Naziv = "Inženjerska grafika 1" },
                        new { ID = 61, FakultetId = 13, NastavnikId = 61, Naziv = "Fonologija hrvatskoga jezika" },
                        new { ID = 62, FakultetId = 13, NastavnikId = 62, Naziv = "Hrvatska književnost srednjovjekovlja" },
                        new { ID = 63, FakultetId = 13, NastavnikId = 63, Naziv = "Hrvatski identitet u europskom kontekstu" },
                        new { ID = 64, FakultetId = 13, NastavnikId = 64, Naziv = "Osnove hrvatske jezične kulture" },
                        new { ID = 65, FakultetId = 13, NastavnikId = 65, Naziv = "Uvod u kroatologiju" },
                        new { ID = 66, FakultetId = 14, NastavnikId = 66, Naziv = "Analitička kemija" },
                        new { ID = 67, FakultetId = 14, NastavnikId = 67, Naziv = "Osnove elektrotehnike" },
                        new { ID = 68, FakultetId = 14, NastavnikId = 68, Naziv = "Opća i anorganska kemija" },
                        new { ID = 69, FakultetId = 14, NastavnikId = 69, Naziv = "Osnove strojarstva" },
                        new { ID = 70, FakultetId = 14, NastavnikId = 70, Naziv = "Bilanca tvari i energije" },
                        new { ID = 71, FakultetId = 15, NastavnikId = 71, Naziv = "Engleski jezik u informatičkoj struci" },
                        new { ID = 72, FakultetId = 15, NastavnikId = 72, Naziv = "Informacijski i računalni sustavi" },
                        new { ID = 73, FakultetId = 15, NastavnikId = 73, Naziv = "Organizacija" },
                        new { ID = 74, FakultetId = 15, NastavnikId = 74, Naziv = "Poslovno komuniciranje" },
                        new { ID = 75, FakultetId = 15, NastavnikId = 75, Naziv = "Programiranje 1" },
                        new { ID = 76, FakultetId = 16, NastavnikId = 76, Naziv = "Uvod u novinarstvo" },
                        new { ID = 77, FakultetId = 16, NastavnikId = 77, Naziv = "Komunikologija" },
                        new { ID = 78, FakultetId = 16, NastavnikId = 78, Naziv = "Mediji i nasilje" },
                        new { ID = 79, FakultetId = 17, NastavnikId = 79, Naziv = "Održavanje vozila javnog gradskog prijevoza" },
                        new { ID = 80, FakultetId = 17, NastavnikId = 80, Naziv = "Vozila za javni gradski prijevoz" },
                        new { ID = 81, FakultetId = 17, NastavnikId = 81, Naziv = "Gradske prometnice" },
                        new { ID = 82, FakultetId = 18, NastavnikId = 82, Naziv = "Matematika I" },
                        new { ID = 83, FakultetId = 18, NastavnikId = 83, Naziv = "Mehanika I" },
                        new { ID = 84, FakultetId = 18, NastavnikId = 84, Naziv = "Materijali I" },
                        new { ID = 85, FakultetId = 18, NastavnikId = 85, Naziv = "Računalna i inženjerska grafika" },
                        new { ID = 86, FakultetId = 19, NastavnikId = 86, Naziv = "Hrvatska povijest" },
                        new { ID = 87, FakultetId = 19, NastavnikId = 87, Naziv = "Nenasilna komunikacija" },
                        new { ID = 88, FakultetId = 19, NastavnikId = 88, Naziv = "Pedagogija" },
                        new { ID = 89, FakultetId = 20, NastavnikId = 89, Naziv = "Uvod u farmaciju" },
                        new { ID = 90, FakultetId = 20, NastavnikId = 90, Naziv = "Matematika sa statističkom analizom" },
                        new { ID = 91, FakultetId = 20, NastavnikId = 91, Naziv = "Stanična biologija s genetikom" },
                        new { ID = 92, FakultetId = 21, NastavnikId = 92, Naziv = "Grčka filozofija I" },
                        new { ID = 93, FakultetId = 21, NastavnikId = 93, Naziv = "Uvod u filozofiju" },
                        new { ID = 94, FakultetId = 21, NastavnikId = 94, Naziv = "Filozofija politike" },
                        new { ID = 95, FakultetId = 22, NastavnikId = 95, Naziv = "Metodologija istraživanja u kulturi" },
                        new { ID = 96, FakultetId = 22, NastavnikId = 96, Naziv = "Uvod u filozofiju" },
                        new { ID = 97, FakultetId = 22, NastavnikId = 97, Naziv = "Uvod u kulturalne studije" },
                        new { ID = 98, FakultetId = 23, NastavnikId = 98, Naziv = "Povijest starih civilizacija" },
                        new { ID = 99, FakultetId = 23, NastavnikId = 99, Naziv = "Povijest Grčke i Rima sa starom poviješću hrvatskih zemalja" },
                        new { ID = 100, FakultetId = 23, NastavnikId = 100, Naziv = "Latinski jezik" },
                        new { ID = 101, FakultetId = 24, NastavnikId = 101, Naziv = "Osnove usmene i pisane kulture" },
                        new { ID = 102, FakultetId = 24, NastavnikId = 102, Naziv = "Osnove informacijske tehnologije" },
                        new { ID = 103, FakultetId = 24, NastavnikId = 103, Naziv = "Pretraživanje informacija" },
                        new { ID = 104, FakultetId = 25, NastavnikId = 104, Naziv = "Biološka psihologija I" },
                        new { ID = 105, FakultetId = 25, NastavnikId = 105, Naziv = "Percepcija i pamćenje" },
                        new { ID = 106, FakultetId = 25, NastavnikId = 106, Naziv = "Psihologija kao znanost i struka" },
                        new { ID = 107, FakultetId = 26, NastavnikId = 107, Naziv = "Geodetski instrumenti" },
                        new { ID = 108, FakultetId = 26, NastavnikId = 108, Naziv = "Inženjerska grafika u geodeziji i geoinformatici" },
                        new { ID = 109, FakultetId = 26, NastavnikId = 109, Naziv = "Analitička geometrija i linearna algebra" },
                        new { ID = 110, FakultetId = 27, NastavnikId = 110, Naziv = "Osnove zaštite okoliša" },
                        new { ID = 111, FakultetId = 27, NastavnikId = 111, Naziv = "Nacrtna geometrija" },
                        new { ID = 112, FakultetId = 27, NastavnikId = 112, Naziv = "Geologija" },
                        new { ID = 113, FakultetId = 28, NastavnikId = 113, Naziv = "Deskriptivna geometrija" },
                        new { ID = 114, FakultetId = 28, NastavnikId = 114, Naziv = "Geodezija" },
                        new { ID = 115, FakultetId = 28, NastavnikId = 115, Naziv = "Matematički programi za inženjere" },
                        new { ID = 116, FakultetId = 29, NastavnikId = 116, Naziv = "Konstrukcijska geometrija" },
                        new { ID = 117, FakultetId = 29, NastavnikId = 117, Naziv = "Uvod u graditeljstvo" },
                        new { ID = 118, FakultetId = 29, NastavnikId = 118, Naziv = "Poznavanje materijala" },
                        new { ID = 119, FakultetId = 30, NastavnikId = 119, Naziv = "Inženjerska grafika" },
                        new { ID = 120, FakultetId = 30, NastavnikId = 120, Naziv = "Tehnička mehanika" },
                        new { ID = 121, FakultetId = 30, NastavnikId = 121, Naziv = "Likovno grafička kultura 1" },
                        new { ID = 122, FakultetId = 31, NastavnikId = 122, Naziv = "Uvod u misterij Krista i povijest spasenja" },
                        new { ID = 123, FakultetId = 31, NastavnikId = 123, Naziv = "Hebrejski jezik" },
                        new { ID = 124, FakultetId = 31, NastavnikId = 124, Naziv = "Opća crkvena povijest, I.: stari i srednji vijek" },
                        new { ID = 125, FakultetId = 32, NastavnikId = 125, Naziv = "Crkvena umjetnost" },
                        new { ID = 126, FakultetId = 32, NastavnikId = 126, Naziv = "Razvojna psihologija" },
                        new { ID = 127, FakultetId = 32, NastavnikId = 127, Naziv = "Uvod u filozofiju" },
                        new { ID = 128, FakultetId = 33, NastavnikId = 128, Naziv = "Patrologija" },
                        new { ID = 129, FakultetId = 33, NastavnikId = 129, Naziv = "Uvod u filozofiju i teologiju" },
                        new { ID = 130, FakultetId = 33, NastavnikId = 130, Naziv = "Opći uvod u Sveto pismo" },
                        new { ID = 131, FakultetId = 34, NastavnikId = 131, Naziv = "Atletika-hodanja i trčanja" },
                        new { ID = 132, FakultetId = 34, NastavnikId = 132, Naziv = "Funkcionalna anatomija" },
                        new { ID = 133, FakultetId = 34, NastavnikId = 133, Naziv = "Osnovne kineziološke transformacije I" },
                        new { ID = 134, FakultetId = 35, NastavnikId = 134, Naziv = "Medicinska biologija" },
                        new { ID = 135, FakultetId = 35, NastavnikId = 135, Naziv = "Medicinska fizika i biofizika" },
                        new { ID = 136, FakultetId = 35, NastavnikId = 136, Naziv = "Medicinska kemija i biokemija" },
                        new { ID = 137, FakultetId = 36, NastavnikId = 137, Naziv = "Uvod u medicinu i povijest medicine" },
                        new { ID = 138, FakultetId = 36, NastavnikId = 138, Naziv = "Socijalna medicina" },
                        new { ID = 139, FakultetId = 36, NastavnikId = 139, Naziv = "Psihološka medicina" },
                        new { ID = 140, FakultetId = 37, NastavnikId = 140, Naziv = "Imunologija i medicinska genetika" },
                        new { ID = 141, FakultetId = 37, NastavnikId = 141, Naziv = "Temelji neuroznanosti" },
                        new { ID = 142, FakultetId = 37, NastavnikId = 142, Naziv = "Fiziologija" },
                        new { ID = 143, FakultetId = 38, NastavnikId = 143, Naziv = "Anatomija" },
                        new { ID = 144, FakultetId = 38, NastavnikId = 144, Naziv = "Medicinska biologija" },
                        new { ID = 145, FakultetId = 38, NastavnikId = 145, Naziv = "Fizika i biofizika" },
                        new { ID = 146, FakultetId = 39, NastavnikId = 146, Naziv = "Matematika 1 " },
                        new { ID = 147, FakultetId = 39, NastavnikId = 147, Naziv = "Fizika" },
                        new { ID = 148, FakultetId = 39, NastavnikId = 148, Naziv = "Uvod u metalurgiju" },
                        new { ID = 149, FakultetId = 40, NastavnikId = 149, Naziv = "Biologija stanice" },
                        new { ID = 150, FakultetId = 40, NastavnikId = 150, Naziv = "Mikrobiologija" },
                        new { ID = 151, FakultetId = 40, NastavnikId = 151, Naziv = "Opća zoologija" },
                        new { ID = 152, FakultetId = 41, NastavnikId = 152, Naziv = "Osnove informatike" },
                        new { ID = 153, FakultetId = 41, NastavnikId = 153, Naziv = "Osnove fizike 1" },
                        new { ID = 154, FakultetId = 41, NastavnikId = 154, Naziv = "Matematika 1" },
                        new { ID = 155, FakultetId = 42, NastavnikId = 155, Naziv = "Programiranje 1" },
                        new { ID = 156, FakultetId = 42, NastavnikId = 156, Naziv = "Osnove informatike" },
                        new { ID = 157, FakultetId = 42, NastavnikId = 157, Naziv = "Multimedijski sustavi" },
                        new { ID = 158, FakultetId = 43, NastavnikId = 158, Naziv = "Poljoprivredna botanika" },
                        new { ID = 159, FakultetId = 43, NastavnikId = 159, Naziv = "Primjena računala u poljoprivredi" },
                        new { ID = 160, FakultetId = 43, NastavnikId = 160, Naziv = "Pedologija" },
                        new { ID = 161, FakultetId = 44, NastavnikId = 161, Naziv = "Brodska elektrotehnika" },
                        new { ID = 162, FakultetId = 44, NastavnikId = 162, Naziv = "Poznavanje broda i plovidbe" },
                        new { ID = 163, FakultetId = 44, NastavnikId = 163, Naziv = "Matematika I" },
                        new { ID = 164, FakultetId = 45, NastavnikId = 164, Naziv = "Teorija prava i države" },
                        new { ID = 165, FakultetId = 45, NastavnikId = 165, Naziv = "Povijest hrvatskog prava i države" },
                        new { ID = 166, FakultetId = 45, NastavnikId = 166, Naziv = "Seminar" },
                        new { ID = 167, FakultetId = 46, NastavnikId = 167, Naziv = "Opća pravna povijest" },
                        new { ID = 168, FakultetId = 46, NastavnikId = 168, Naziv = "Socijologija" },
                        new { ID = 169, FakultetId = 46, NastavnikId = 169, Naziv = "Politička ekonomija" },
                        new { ID = 170, FakultetId = 47, NastavnikId = 170, Naziv = "Opća povijest prava i države" },
                        new { ID = 171, FakultetId = 47, NastavnikId = 171, Naziv = "Rimsko privatno pravo" },
                        new { ID = 172, FakultetId = 47, NastavnikId = 172, Naziv = "Hrvatska pravna povijest u europskom kontekstu" },
                        new { ID = 173, FakultetId = 48, NastavnikId = 173, Naziv = "Opća kemija" },
                        new { ID = 174, FakultetId = 48, NastavnikId = 174, Naziv = "Uvod u prehrambene tehnologije" },
                        new { ID = 175, FakultetId = 48, NastavnikId = 175, Naziv = "Organska kemija" },
                        new { ID = 176, FakultetId = 49, NastavnikId = 176, Naziv = "Opća i anorganska kemija" },
                        new { ID = 177, FakultetId = 49, NastavnikId = 177, Naziv = "Analitička kemija" },
                        new { ID = 178, FakultetId = 49, NastavnikId = 178, Naziv = "Tehnička fizika" },
                        new { ID = 179, FakultetId = 50, NastavnikId = 179, Naziv = "Osnove matematike" },
                        new { ID = 180, FakultetId = 50, NastavnikId = 180, Naziv = "Uvod u algebru s analitičkom geometrijom" },
                        new { ID = 181, FakultetId = 50, NastavnikId = 181, Naziv = "Programiranje I" },
                        new { ID = 182, FakultetId = 51, NastavnikId = 182, Naziv = "Matematika" },
                        new { ID = 183, FakultetId = 51, NastavnikId = 183, Naziv = "Opća zoologija" },
                        new { ID = 184, FakultetId = 51, NastavnikId = 184, Naziv = "Stanična i molekularna biologija" },
                        new { ID = 185, FakultetId = 52, NastavnikId = 185, Naziv = "Histologija s embriologijom" },
                        new { ID = 186, FakultetId = 52, NastavnikId = 186, Naziv = "Uvod u dentalnu medicinu" },
                        new { ID = 187, FakultetId = 52, NastavnikId = 187, Naziv = "Stanična biologija s genetikom" },
                        new { ID = 188, FakultetId = 53, NastavnikId = 188, Naziv = "Alati i naprave I" },
                        new { ID = 189, FakultetId = 53, NastavnikId = 189, Naziv = "Automatizacija" },
                        new { ID = 190, FakultetId = 53, NastavnikId = 190, Naziv = "Čvrstoća" },
                        new { ID = 191, FakultetId = 54, NastavnikId = 191, Naziv = "Kemija s biokemijom" },
                        new { ID = 192, FakultetId = 54, NastavnikId = 192, Naziv = "Zoologija u šumarstvu" },
                        new { ID = 193, FakultetId = 54, NastavnikId = 193, Naziv = "Petrologija s geologijom" },
                        new { ID = 194, FakultetId = 55, NastavnikId = 194, Naziv = "Programiranje" },
                        new { ID = 195, FakultetId = 55, NastavnikId = 195, Naziv = "Objektno orijentirano programiranje" },
                        new { ID = 196, FakultetId = 55, NastavnikId = 196, Naziv = "Uvod u web tehnologije	" },
                        new { ID = 197, FakultetId = 55, NastavnikId = 197, Naziv = "Algoritmi i strukture podataka" },
                        new { ID = 198, FakultetId = 55, NastavnikId = 198, Naziv = "Operacijski sustavi" },
                        new { ID = 199, FakultetId = 55, NastavnikId = 199, Naziv = "Programiranje u jeziku Java" },
                        new { ID = 200, FakultetId = 56, NastavnikId = 200, Naziv = "Pedagogija ranoga odgoja 1" },
                        new { ID = 201, FakultetId = 56, NastavnikId = 201, Naziv = "Razvojna psihologija 1" },
                        new { ID = 202, FakultetId = 56, NastavnikId = 202, Naziv = "Glazbena kultura" },
                        new { ID = 203, FakultetId = 57, NastavnikId = 203, Naziv = "Uvod u veterinarstvo" },
                        new { ID = 204, FakultetId = 57, NastavnikId = 204, Naziv = "Anatomija s organogenezom domaćih životinja" },
                        new { ID = 205, FakultetId = 57, NastavnikId = 205, Naziv = "Botanika u veterinarskoj medicini" }
                    );
                });

            modelBuilder.Entity("Studomat.MODEL.Mjesto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivMjesta");

                    b.Property<int?>("ZupanijaId");

                    b.HasKey("ID");

                    b.HasIndex("ZupanijaId");

                    b.ToTable("Mjesta");

                    b.HasData(
                        new { ID = 1, NazivMjesta = "Zagreb", ZupanijaId = 21 },
                        new { ID = 2, NazivMjesta = "Split", ZupanijaId = 17 },
                        new { ID = 3, NazivMjesta = "Rijeka", ZupanijaId = 8 },
                        new { ID = 4, NazivMjesta = "Osijek", ZupanijaId = 14 },
                        new { ID = 5, NazivMjesta = "Zadar", ZupanijaId = 13 },
                        new { ID = 6, NazivMjesta = "Slavonski Brod", ZupanijaId = 12 },
                        new { ID = 7, NazivMjesta = "Pula", ZupanijaId = 18 },
                        new { ID = 8, NazivMjesta = "Otočac", ZupanijaId = 9 },
                        new { ID = 9, NazivMjesta = "Kaštela", ZupanijaId = 17 },
                        new { ID = 10, NazivMjesta = "Karlovac", ZupanijaId = 4 },
                        new { ID = 11, NazivMjesta = "Sisak", ZupanijaId = 3 },
                        new { ID = 12, NazivMjesta = "Dubrovnik", ZupanijaId = 19 },
                        new { ID = 13, NazivMjesta = "Varaždin", ZupanijaId = 5 },
                        new { ID = 14, NazivMjesta = "Šibenik", ZupanijaId = 15 },
                        new { ID = 15, NazivMjesta = "Velika Gorica", ZupanijaId = 1 },
                        new { ID = 16, NazivMjesta = "Vinkovci", ZupanijaId = 16 },
                        new { ID = 17, NazivMjesta = "Vukovar", ZupanijaId = 16 },
                        new { ID = 18, NazivMjesta = "Bjelovar", ZupanijaId = 7 },
                        new { ID = 19, NazivMjesta = "Koprivnica", ZupanijaId = 6 },
                        new { ID = 20, NazivMjesta = "Đakovo", ZupanijaId = 14 },
                        new { ID = 21, NazivMjesta = "Požega", ZupanijaId = 11 },
                        new { ID = 22, NazivMjesta = "Zaprešić", ZupanijaId = 1 },
                        new { ID = 23, NazivMjesta = "Solin", ZupanijaId = 17 },
                        new { ID = 24, NazivMjesta = "Čakovec", ZupanijaId = 20 },
                        new { ID = 25, NazivMjesta = "Virovitica", ZupanijaId = 10 },
                        new { ID = 26, NazivMjesta = "Samobor", ZupanijaId = 1 },
                        new { ID = 27, NazivMjesta = "Kutina", ZupanijaId = 3 },
                        new { ID = 28, NazivMjesta = "Metković", ZupanijaId = 19 },
                        new { ID = 29, NazivMjesta = "Petrinja", ZupanijaId = 3 },
                        new { ID = 30, NazivMjesta = "Županja", ZupanijaId = 16 },
                        new { ID = 31, NazivMjesta = "Rovinj", ZupanijaId = 18 },
                        new { ID = 32, NazivMjesta = "Makarska", ZupanijaId = 17 },
                        new { ID = 33, NazivMjesta = "Nova Gradiška", ZupanijaId = 12 },
                        new { ID = 34, NazivMjesta = "Križevci", ZupanijaId = 6 },
                        new { ID = 35, NazivMjesta = "Sinj", ZupanijaId = 17 },
                        new { ID = 36, NazivMjesta = "Knin", ZupanijaId = 15 },
                        new { ID = 37, NazivMjesta = "Slatina", ZupanijaId = 10 },
                        new { ID = 38, NazivMjesta = "Trogir", ZupanijaId = 17 },
                        new { ID = 39, NazivMjesta = "Poreč", ZupanijaId = 18 },
                        new { ID = 40, NazivMjesta = "Sveta Nedelja", ZupanijaId = 1 },
                        new { ID = 41, NazivMjesta = "Dugo Selo", ZupanijaId = 1 },
                        new { ID = 42, NazivMjesta = "Našice", ZupanijaId = 14 },
                        new { ID = 43, NazivMjesta = "Jastrebarsko", ZupanijaId = 1 },
                        new { ID = 44, NazivMjesta = "Omiš", ZupanijaId = 17 },
                        new { ID = 45, NazivMjesta = "Vrbovec", ZupanijaId = 1 },
                        new { ID = 46, NazivMjesta = "Gospić", ZupanijaId = 9 },
                        new { ID = 47, NazivMjesta = "Krapina", ZupanijaId = 2 },
                        new { ID = 48, NazivMjesta = "Delnice", ZupanijaId = 8 },
                        new { ID = 49, NazivMjesta = "Ogulin", ZupanijaId = 4 },
                        new { ID = 50, NazivMjesta = "Opatija", ZupanijaId = 8 },
                        new { ID = 51, NazivMjesta = "Pazin", ZupanijaId = 18 },
                        new { ID = 52, NazivMjesta = "Pakrac", ZupanijaId = 11 },
                        new { ID = 53, NazivMjesta = "Drniš", ZupanijaId = 15 },
                        new { ID = 54, NazivMjesta = "Senj", ZupanijaId = 9 },
                        new { ID = 55, NazivMjesta = "Beli Manastir", ZupanijaId = 14 },
                        new { ID = 56, NazivMjesta = "Imotski", ZupanijaId = 17 },
                        new { ID = 57, NazivMjesta = "Ploče", ZupanijaId = 19 },
                        new { ID = 58, NazivMjesta = "Crikvenica", ZupanijaId = 8 },
                        new { ID = 59, NazivMjesta = "Ozalj", ZupanijaId = 4 }
                    );
                });

            modelBuilder.Entity("Studomat.MODEL.Nastavnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Ime");

                    b.Property<string>("Lozinka");

                    b.Property<int?>("MjestoId");

                    b.Property<string>("Prezime");

                    b.Property<string>("TitulaIspred");

                    b.Property<string>("TitulaIza");

                    b.HasKey("ID");

                    b.HasIndex("MjestoId");

                    b.ToTable("Nastavnici");

                    b.HasData(
                        new { ID = 1, Ime = "Sanja", MjestoId = 1, Prezime = "Sikora", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 2, Ime = "Mihaela", MjestoId = 2, Prezime = "Britvec", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 3, Ime = "Ivo", MjestoId = 3, Prezime = "Grgić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 4, Ime = "Marina", MjestoId = 4, Prezime = "Ninčević", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 5, Ime = "Milan", MjestoId = 5, Prezime = "Mesić", TitulaIspred = "Mag.oec" },
                        new { ID = 6, Ime = "Korina", MjestoId = 1, Prezime = "Hunjak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 7, Ime = "Siniša", MjestoId = 1, Prezime = "Majkus", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 8, Ime = "Elvis", MjestoId = 2, Prezime = "Krstulović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 9, Ime = "Goran", MjestoId = 3, Prezime = "Štimac", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 10, Ime = "Marina", MjestoId = 4, Prezime = "Banić-Zrinšćak", TitulaIspred = "Mag.oec" },
                        new { ID = 11, Ime = "Željka", MjestoId = 5, Prezime = "Lapuh", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 12, Ime = "Daniel", MjestoId = 6, Prezime = "Jurić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 13, Ime = "Nikola", MjestoId = 5, Prezime = "Bilić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 14, Ime = "Laura", MjestoId = 6, Prezime = "Konda Labaš", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 15, Ime = "Marin", MjestoId = 1, Prezime = "Bačić", TitulaIspred = "Mag.oec" },
                        new { ID = 16, Ime = "Emilija", MjestoId = 1, Prezime = "Duparova", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 17, Ime = "Dajana", MjestoId = 3, Prezime = "Radoš", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 18, Ime = "Marin", MjestoId = 2, Prezime = "Lukanović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 19, Ime = "Robert", MjestoId = 1, Prezime = "Mijalić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 20, Ime = "Valentina", MjestoId = 2, Prezime = "Lončarić", TitulaIspred = "Mag.oec" },
                        new { ID = 21, Ime = "Davor", MjestoId = 1, Prezime = "Andrić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 22, Ime = "Gorana", MjestoId = 6, Prezime = "Aras Gazić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 23, Ime = "Dubravko", MjestoId = 5, Prezime = "Bačić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 24, Ime = "Ana Martina", MjestoId = 4, Prezime = "Bakić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 25, Ime = "Alan", MjestoId = 2, Prezime = "Braun", TitulaIspred = "Mag.oec" },
                        new { ID = 26, Ime = "Marko", MjestoId = 1, Prezime = "Obad Šćitaroci", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 27, Ime = "Tin", MjestoId = 2, Prezime = "Oberman", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 28, Ime = "Veljko", MjestoId = 1, Prezime = "Oluić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 29, Ime = "Milan", MjestoId = 1, Prezime = "Opalić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 30, Ime = "Mladen", MjestoId = 1, Prezime = "Orešić", TitulaIspred = "Mag.oec" },
                        new { ID = 31, Ime = "Ivan", MjestoId = 2, Prezime = "Ferenčak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 32, Ime = "Branko", MjestoId = 3, Prezime = "Crnković", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 33, Ime = "Josip", MjestoId = 2, Prezime = "Horvat", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 34, Ime = "Jasna", MjestoId = 4, Prezime = "Mijoč", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 35, Ime = "Željka", MjestoId = 4, Prezime = "Turkalj", TitulaIspred = "Mag.oec" },
                        new { ID = 36, Ime = "Ivana", MjestoId = 6, Prezime = "Fosić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 37, Ime = "Aleks", MjestoId = 3, Prezime = "Živković", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 38, Ime = "Alma", MjestoId = 4, Prezime = "Šundalić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 39, Ime = "Ljiljana", MjestoId = 3, Prezime = "Radoš", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 40, Ime = "Karlo", MjestoId = 3, Prezime = "Knežević", TitulaIspred = "Mag.oec" },
                        new { ID = 41, Ime = "Branka", MjestoId = 1, Prezime = "Marasović", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 42, Ime = "Snježana", MjestoId = 3, Prezime = "Pivac", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 43, Ime = "Marija", MjestoId = 2, Prezime = "Šimić Šarić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 44, Ime = "Tino", MjestoId = 6, Prezime = "Kusanović", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 45, Ime = "Tina", MjestoId = 7, Prezime = "Vuko", TitulaIspred = "Mag.oec" },
                        new { ID = 46, Ime = "Vinko", MjestoId = 7, Prezime = "Glavinić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 47, Ime = "Ana", MjestoId = 3, Prezime = "Aglić Aljinović", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 48, Ime = "Tajana", MjestoId = 5, Prezime = "Burić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 49, Ime = "Goran", MjestoId = 4, Prezime = "Gledec", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 50, Ime = "Ivan", MjestoId = 1, Prezime = "Botički", TitulaIspred = "Mag.oec" },
                        new { ID = 51, Ime = "Dragan", MjestoId = 1, Prezime = "Vulin", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 52, Ime = "Marinko", MjestoId = 1, Prezime = "Barukčić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 53, Ime = "Ivan", MjestoId = 2, Prezime = "Biondić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 54, Ime = "Luka", MjestoId = 2, Prezime = "Filipović", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 55, Ime = "Tomislav", MjestoId = 2, Prezime = "Matić", TitulaIspred = "Mag.oec" },
                        new { ID = 56, Ime = "Jani", MjestoId = 1, Prezime = "Barle", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 57, Ime = "Ivan", MjestoId = 1, Prezime = "Jadrić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 58, Ime = "Josip", MjestoId = 1, Prezime = "Eterović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 59, Ime = "Dario", MjestoId = 1, Prezime = "Bezmalinović", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 60, Ime = "Ivan", MjestoId = 1, Prezime = "Tolj", TitulaIspred = "Mag.oec" },
                        new { ID = 61, Ime = "Slavko", MjestoId = 1, Prezime = "Vulić Vranković", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 62, Ime = "Velimir", MjestoId = 3, Prezime = "Franić Tomić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 63, Ime = "Stanko", MjestoId = 1, Prezime = "Tadić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 64, Ime = "Ivan", MjestoId = 1, Prezime = "Kresnik", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 65, Ime = "Daniel", MjestoId = 1, Prezime = "Piskač", TitulaIspred = "Mag.oec" },
                        new { ID = 66, Ime = "Branimir", MjestoId = 2, Prezime = "Zelić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 67, Ime = "Nikola", MjestoId = 3, Prezime = "Bolf", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 68, Ime = "Vlatka", MjestoId = 4, Prezime = "Filipan", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 69, Ime = "Šime", MjestoId = 1, Prezime = "Ukić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 70, Ime = "Elvira", MjestoId = 4, Prezime = "Begović Kovač", TitulaIspred = "Mag.oec" },
                        new { ID = 71, Ime = "Marijana", MjestoId = 1, Prezime = "Ćurak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 72, Ime = "Ana", MjestoId = 3, Prezime = "Rimac Smiljanić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 73, Ime = "Goran", MjestoId = 2, Prezime = "Matijašić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 74, Ime = "Janko", MjestoId = 1, Prezime = "Peršun", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 75, Ime = "Vlado", MjestoId = 5, Prezime = "Tomašić", TitulaIspred = "Mag.oec" },
                        new { ID = 76, Ime = "Mario", MjestoId = 5, Prezime = "Konecki", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 77, Ime = "Andreja", MjestoId = 3, Prezime = "Kovačić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 78, Ime = "Igor", MjestoId = 2, Prezime = "Balaban", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 79, Ime = "Nikola", MjestoId = 1, Prezime = "Ivković", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 80, Ime = "Ivan", MjestoId = 2, Prezime = "Magdalenić", TitulaIspred = "Mag.oec" },
                        new { ID = 81, Ime = "Luka", MjestoId = 5, Prezime = "Milić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 82, Ime = "Aleksandra", MjestoId = 3, Prezime = "Sobodić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 83, Ime = "Miran", MjestoId = 2, Prezime = "Zlatović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 84, Ime = "Elvis", MjestoId = 5, Prezime = "Popović", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 85, Ime = "Danijel", MjestoId = 2, Prezime = "Filipović", TitulaIspred = "Mag.oec" },
                        new { ID = 86, Ime = "Blaženka", MjestoId = 1, Prezime = "Divjak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 87, Ime = "Zlatko", MjestoId = 3, Prezime = "Erjavec", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 88, Ime = "Marcel", MjestoId = 2, Prezime = "Maretić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 89, Ime = "Damjan", MjestoId = 1, Prezime = "Klemenčić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 90, Ime = "Mihaela", MjestoId = 2, Prezime = "Laljek", TitulaIspred = "Mag.oec" },
                        new { ID = 91, Ime = "Lucija", MjestoId = 1, Prezime = "Žignić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 92, Ime = "Ivan", MjestoId = 3, Prezime = "Malbašić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 93, Ime = "Anamarija", MjestoId = 2, Prezime = "Jelaković", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 94, Ime = "Nikolina", MjestoId = 1, Prezime = "Posarić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 95, Ime = "Valentina", MjestoId = 2, Prezime = "Kolačko", TitulaIspred = "Mag.oec" },
                        new { ID = 96, Ime = "Emina", MjestoId = 1, Prezime = "Crleni", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 97, Ime = "Goran", MjestoId = 3, Prezime = "Bubaš", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 98, Ime = "Violeta", MjestoId = 2, Prezime = "Vidaček-Hainš", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 99, Ime = "Antonela", MjestoId = 5, Prezime = "Čižmešija", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 100, Ime = "Ana", MjestoId = 4, Prezime = "Kutnjak", TitulaIspred = "Mag.oec" },
                        new { ID = 101, Ime = "Dijana", MjestoId = 1, Prezime = "Plantak Vukovac", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 102, Ime = "Robert", MjestoId = 3, Prezime = "Kudelić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 103, Ime = "Damir", MjestoId = 2, Prezime = "Vučić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 104, Ime = "Kornelije", MjestoId = 5, Prezime = "Rabuzin", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 105, Ime = "Snježana", MjestoId = 4, Prezime = "Križanić", TitulaIspred = "Mag.oec" },
                        new { ID = 106, Ime = "Bogdan", MjestoId = 1, Prezime = "Okreša Đurić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 107, Ime = "Stjepan", MjestoId = 3, Prezime = "Dvorski", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 108, Ime = "Vladimir", MjestoId = 2, Prezime = "Kovšca", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 109, Ime = "Ivana", MjestoId = 5, Prezime = "Dvorski Lacković", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 110, Ime = "Suzana", MjestoId = 4, Prezime = "Keglević Kozjak", TitulaIspred = "Mag.oec" },
                        new { ID = 111, Ime = "Meri", MjestoId = 1, Prezime = "Tadinac", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 112, Ime = "Katarina", MjestoId = 3, Prezime = "Faraguna", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 113, Ime = "Andrea", MjestoId = 2, Prezime = "Vranić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 114, Ime = "Ivana", MjestoId = 5, Prezime = "Hromatko", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 115, Ime = "Dragutin", MjestoId = 4, Prezime = "Ivanec", TitulaIspred = "Mag.oec" },
                        new { ID = 116, Ime = "Marina", MjestoId = 1, Prezime = "Martinčević", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 117, Ime = "Denis", MjestoId = 3, Prezime = "Bratko", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 118, Ime = "Dragutin", MjestoId = 2, Prezime = "Ivanec", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 119, Ime = " Francesca", MjestoId = 5, Prezime = "Dumančić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 120, Ime = "Denis", MjestoId = 4, Prezime = "Vlašiček", TitulaIspred = "Mag.oec" },
                        new { ID = 121, Ime = "Vesna", MjestoId = 1, Prezime = "Alikalfić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 122, Ime = "Svetlana", MjestoId = 3, Prezime = "Božić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 123, Ime = "Mirjana", MjestoId = 2, Prezime = "Tonković", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 124, Ime = "Tina", MjestoId = 5, Prezime = "Miholjančan", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 125, Ime = "Jasna", MjestoId = 4, Prezime = "Ćirić", TitulaIspred = "Mag.oec" },
                        new { ID = 126, Ime = "Predrag", MjestoId = 1, Prezime = "Lončar", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 127, Ime = "Sanja", MjestoId = 3, Prezime = "Kovač", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 128, Ime = "Mladen", MjestoId = 2, Prezime = "Božičević", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 129, Ime = "Mario", MjestoId = 5, Prezime = "Šiljeg", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 130, Ime = "Lucija", MjestoId = 4, Prezime = "Radetić", TitulaIspred = "Mag.oec" },
                        new { ID = 131, Ime = "Zrinka", MjestoId = 1, Prezime = "Lacković Vincek", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 132, Ime = "Ema", MjestoId = 3, Prezime = "Novak", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 133, Ime = "Nina", MjestoId = 2, Prezime = "Begičević Ređep", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 134, Ime = "Nikola", MjestoId = 5, Prezime = "Kadoić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 135, Ime = "Barbara", MjestoId = 4, Prezime = "Šlibar", TitulaIspred = "Mag.oec" },
                        new { ID = 136, Ime = "Mladen", MjestoId = 1, Prezime = "Konecki", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 137, Ime = "Danijel", MjestoId = 3, Prezime = "Radošević", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 138, Ime = "Vladimir", MjestoId = 2, Prezime = "Bermanec", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 139, Ime = "Zoran", MjestoId = 5, Prezime = "Glavaš", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 140, Ime = "Mirko", MjestoId = 4, Prezime = "Gojić", TitulaIspred = "Mag.oec" },
                        new { ID = 141, Ime = "Damir", MjestoId = 1, Prezime = "Hršak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 142, Ime = "Stjepan", MjestoId = 3, Prezime = "Kožuh", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 143, Ime = "Ladislav", MjestoId = 2, Prezime = "Lazić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 144, Ime = "Anita", MjestoId = 5, Prezime = "Begić Hadžipašić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 145, Ime = "Ivan", MjestoId = 4, Prezime = "Brnardić", TitulaIspred = "Mag.oec" },
                        new { ID = 146, Ime = "Natalija", MjestoId = 1, Prezime = "Dolić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 147, Ime = "Tamara", MjestoId = 3, Prezime = "Holjevac Grgurić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 148, Ime = "Robert", MjestoId = 2, Prezime = "Pezer", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 149, Ime = "Ljerka", MjestoId = 5, Prezime = "Slokar Benić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 150, Ime = "Anita", MjestoId = 4, Prezime = "Štrkalj", TitulaIspred = "Mag.oec" },
                        new { ID = 151, Ime = "Zdenka", MjestoId = 1, Prezime = "Zovko Brodarac", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 152, Ime = "Jakov", MjestoId = 3, Prezime = "Baleta", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 153, Ime = "Ivana", MjestoId = 2, Prezime = "Ivanić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 154, Ime = "Ivan", MjestoId = 5, Prezime = "Ivec", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 155, Ime = "Ivan", MjestoId = 4, Prezime = "Jandrlić", TitulaIspred = "Mag.oec" },
                        new { ID = 156, Ime = "Martina", MjestoId = 1, Prezime = "Lovrenić-Jugović", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 157, Ime = "Vesna", MjestoId = 3, Prezime = "Ocelić Bulatović", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 158, Ime = "Sandra", MjestoId = 2, Prezime = "Brajčinović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 159, Ime = "Tin", MjestoId = 5, Prezime = "Brlić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 160, Ime = "Damijan", MjestoId = 4, Prezime = "Cerinski", TitulaIspred = "Mag.oec" },
                        new { ID = 161, Ime = "Igor", MjestoId = 1, Prezime = "Jajčinović", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 162, Ime = "Barbara", MjestoId = 3, Prezime = "Tubić Bulat", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 163, Ime = "Selim", MjestoId = 2, Prezime = "Pašić", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 164, Ime = "Vibor", MjestoId = 5, Prezime = "Roje", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 165, Ime = "Darko", MjestoId = 4, Prezime = "Bakšić", TitulaIspred = "Mag.oec" },
                        new { ID = 166, Ime = "Ivan", MjestoId = 1, Prezime = "Perković", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 167, Ime = "Azra", MjestoId = 3, Prezime = "Tafo", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 168, Ime = "Anamarija", MjestoId = 2, Prezime = "Jazbec", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 169, Ime = "Mario", MjestoId = 5, Prezime = "Božić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 170, Ime = "Dunja", MjestoId = 4, Prezime = "Aljinović", TitulaIspred = "Mag.oec" },
                        new { ID = 171, Ime = "Bojan", MjestoId = 1, Prezime = "Matoš", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 172, Ime = "Nikola", MjestoId = 3, Prezime = "Pernar", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 173, Ime = "Tomislav", MjestoId = 2, Prezime = "Poršinsky", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 174, Ime = "Boris", MjestoId = 5, Prezime = "Hrašovec", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 175, Ime = "Mario ", MjestoId = 4, Prezime = "Šporčić", TitulaIspred = "Mag.oec" },
                        new { ID = 176, Ime = "Jelena", MjestoId = 1, Prezime = "Kolić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 177, Ime = "Tomislav", MjestoId = 3, Prezime = "Sinković", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 178, Ime = "Marin", MjestoId = 2, Prezime = "Hasan", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 179, Ime = "Daniel", MjestoId = 5, Prezime = "Krstonošić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 180, Ime = "Krunoslav", MjestoId = 4, Prezime = "Sever", TitulaIspred = "Mag.oec" },
                        new { ID = 181, Ime = "Željko", MjestoId = 1, Prezime = "Zečić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 182, Ime = "Andreja", MjestoId = 3, Prezime = "Đuka", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 183, Ime = "Krešimir", MjestoId = 2, Prezime = "Krapinec", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 184, Ime = "Ivan", MjestoId = 5, Prezime = "Mlinar", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 185, Ime = "Kajba", MjestoId = 4, Prezime = "Davorin", TitulaIspred = "Mag.oec" },
                        new { ID = 186, Ime = "Roman", MjestoId = 1, Prezime = "Rosavec", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 187, Ime = "Ivica", MjestoId = 3, Prezime = "Tikvić", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 188, Ime = "Lea", MjestoId = 2, Prezime = "Petrović Krajnik", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 189, Ime = "Igor", MjestoId = 5, Prezime = "Poljak", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 190, Ime = "Ernest", MjestoId = 4, Prezime = "Goršić", TitulaIspred = "Mag.oec" },
                        new { ID = 191, Ime = "Marilena", MjestoId = 1, Prezime = "Idžojtić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 192, Ime = "Ante", MjestoId = 3, Prezime = "Seletković", TitulaIspred = "Izv.prof.dr.sc." },
                        new { ID = 193, Ime = "Anka Ozana", MjestoId = 2, Prezime = "Čavlović", TitulaIspred = "Univ.spec.st.eur." },
                        new { ID = 194, Ime = "Ivan", MjestoId = 1, Prezime = "Cesar", TitulaIspred = "Mag.oec" },
                        new { ID = 195, Ime = "Miroslav", MjestoId = 1, Prezime = "Slamić", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 196, Ime = "Sanja", MjestoId = 1, Prezime = "Kraljević", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 197, Ime = "Željko", MjestoId = 1, Prezime = "Kovačević", TitulaIspred = "Mag.oec" },
                        new { ID = 198, Ime = "Davor", MjestoId = 1, Prezime = "Cafuta", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 199, Ime = "Aleksander", MjestoId = 1, Prezime = "Radovan", TitulaIspred = "Mag.oec" },
                        new { ID = 200, Ime = "Anka", MjestoId = 1, Prezime = "Jurčević Lozančić", TitulaIspred = "Mag.oec" },
                        new { ID = 201, Ime = "Ivana", MjestoId = 2, Prezime = "Golik Homolak", TitulaIspred = "Prof.dr.sc." },
                        new { ID = 202, Ime = "Diana", MjestoId = 3, Prezime = "Zalar", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 203, Ime = "Branimir", MjestoId = 4, Prezime = "Stojanović", TitulaIspred = "Mag.oec" },
                        new { ID = 204, Ime = "Blaženka", MjestoId = 5, Prezime = "Bačlija Sušić", TitulaIspred = "Doc.dr.sc." },
                        new { ID = 205, Ime = "Danijel", MjestoId = 6, Prezime = "Žabčić", TitulaIspred = "Mag.oec" }
                    );
                });

            modelBuilder.Entity("Studomat.MODEL.Ocjene", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppUserId");

                    b.Property<DateTime>("DatumPolaganja");

                    b.Property<int?>("KolegijId");

                    b.Property<int>("Ocjena");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("KolegijId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("Studomat.MODEL.Zupanija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivZupanija");

                    b.HasKey("ID");

                    b.ToTable("Zupanije");

                    b.HasData(
                        new { ID = 1, NazivZupanija = "Zagrebačka" },
                        new { ID = 2, NazivZupanija = "Krapinsko-zagorska" },
                        new { ID = 3, NazivZupanija = "Sisačko-moslavačka" },
                        new { ID = 4, NazivZupanija = "Karlovačka" },
                        new { ID = 5, NazivZupanija = "Varaždinska" },
                        new { ID = 6, NazivZupanija = "Koprivničko-križevačka" },
                        new { ID = 7, NazivZupanija = "Bjelovarsko-bilogorska" },
                        new { ID = 8, NazivZupanija = "Primorsko-goranska" },
                        new { ID = 9, NazivZupanija = "Ličko-senjska" },
                        new { ID = 10, NazivZupanija = "Virovitičko-podravska" },
                        new { ID = 11, NazivZupanija = "Požeško-slavonska" },
                        new { ID = 12, NazivZupanija = "Brodsko-posavska" },
                        new { ID = 13, NazivZupanija = "Zadarska" },
                        new { ID = 14, NazivZupanija = "Osječko-baranjska" },
                        new { ID = 15, NazivZupanija = "Šibensko-kninska" },
                        new { ID = 16, NazivZupanija = "Vukovarsko-srijemska" },
                        new { ID = 17, NazivZupanija = "Splitsko-dalmatinska" },
                        new { ID = 18, NazivZupanija = "Istarska" },
                        new { ID = 19, NazivZupanija = "Dubrovačko-neretvanska" },
                        new { ID = 20, NazivZupanija = "Međimurska" },
                        new { ID = 21, NazivZupanija = "Grad Zagreb" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Studomat.MODEL.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Studomat.MODEL.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Studomat.MODEL.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Studomat.MODEL.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Studomat.MODEL.AppUser", b =>
                {
                    b.HasOne("Studomat.MODEL.Fakultet", "Fakultet")
                        .WithMany("AppUsers")
                        .HasForeignKey("FakultetId");

                    b.HasOne("Studomat.MODEL.Mjesto", "Mjesto")
                        .WithMany("AppUsers")
                        .HasForeignKey("MjestoId");
                });

            modelBuilder.Entity("Studomat.MODEL.Fakultet", b =>
                {
                    b.HasOne("Studomat.MODEL.Mjesto", "Mjesto")
                        .WithMany("Fakulteti")
                        .HasForeignKey("MjestoId");
                });

            modelBuilder.Entity("Studomat.MODEL.Kolegij", b =>
                {
                    b.HasOne("Studomat.MODEL.Fakultet", "Fakultet")
                        .WithMany("Kolegiji")
                        .HasForeignKey("FakultetId");

                    b.HasOne("Studomat.MODEL.Nastavnik", "Nastavnik")
                        .WithMany("Kolegiji")
                        .HasForeignKey("NastavnikId");
                });

            modelBuilder.Entity("Studomat.MODEL.Mjesto", b =>
                {
                    b.HasOne("Studomat.MODEL.Zupanija", "Zupanija")
                        .WithMany("Mjesta")
                        .HasForeignKey("ZupanijaId");
                });

            modelBuilder.Entity("Studomat.MODEL.Nastavnik", b =>
                {
                    b.HasOne("Studomat.MODEL.Mjesto", "Mjesto")
                        .WithMany("Nastavnici")
                        .HasForeignKey("MjestoId");
                });

            modelBuilder.Entity("Studomat.MODEL.Ocjene", b =>
                {
                    b.HasOne("Studomat.MODEL.AppUser", "AppUser")
                        .WithMany("Ocjenes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("Studomat.MODEL.Kolegij", "Kolegij")
                        .WithMany("Ocjenes")
                        .HasForeignKey("KolegijId");
                });
#pragma warning restore 612, 618
        }
    }
}
